feat: cli mock testing
sasjs/server pull request #306
Opened 2022-10-11 16:42 UTC by medjedovicm

## Intent

- Mocking structure improved
- Added `add a "STATIC_MOCK_LOCATION=" param to .env`
- Minified mock responses
- Added mocks in separate repo. [@sasjs/mocks](https://github.com/sasjs/mocks)

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [x] Reviewer is assigned.

2022-10-11 22:52 UTC, allanbowe commented on api/src/routes/web/sas9-web.ts
> +  dest: path.join(process.cwd(), mockPath, 'sas9', 'files-recieved')
typo - `files-received`

2022-10-25 10:54 UTC, sabhas requested changes

2022-10-25 10:54 UTC, sabhas commented on api/src/app.ts
> +  app.use(express.urlencoded({ extended: true }))
this line is redundant

2022-10-25 10:54 UTC, sabhas commented on api/src/controllers/mock-sas9.ts
> +    let password = req.query._password?.toString() || undefined
use const instead of let

2022-10-25 10:54 UTC, sabhas commented on api/src/controllers/mock-sas9.ts
> +    let program = req.query._program?.toString() || undefined
use const instead of let

2022-10-25 10:54 UTC, sabhas commented on api/src/controllers/mock-sas9.ts
> +    let filePath: string[] = ['generic', 'sas-stored-process']
```suggestion
    const filePath: string[] = program ? program.replace('/', '').split('/') : ['generic', 'sas-stored-process']
```

2022-10-25 10:54 UTC, sabhas commented on api/src/controllers/mock-sas9.ts
> +    let password = req.query._password?.toString() || undefined
use const

2022-10-25 10:54 UTC, sabhas commented on api/src/controllers/mock-sas9.ts
> +    let filePath: string[] = ['generic', 'sas-stored-process']
use const

2022-10-28 10:00 UTC, sabhas approved these changes

2022-10-28 10:01 UTC, merged