Improve SAS log
sasjs/server pull request #351
Opened 2023-04-11 11:35 UTC by YuryShkoda

## Issue

Closes #346 

## Intent

- Display error and warning icons in `Log` tab if the run time is `SAS`.
- Display error/warning tree at the top of the log if the run time is `SAS`.
- Change error/warning font color within the log if the run time is `SAS`.

## Implementation

- Added `web/src/containers/Studio/internal/components/log/logComponent.tsx`.
- Added `web/src/containers/Studio/internal/components/log/logTabWithIcons.tsx`.
- Added `web/src/utils/log.ts`.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] Reviewer is assigned.

2023-04-11 12:47 UTC, sabhas commented on web/src/containers/Studio/internal/hooks/useEditor.ts
> +  const [selectedRunTime, setSelectedRunTime] = useState<RunTimeType>(
@YuryShkoda you are setting sas as selected runtime by default. What will be the impact if sas is not an option at all?

2023-04-11 13:06 UTC, sabhas commented on web/src/containers/Studio/internal/hooks/useEditor.ts
> +  const [selectedRunTime, setSelectedRunTime] = useState<RunTimeType>(
here is a pic for reference.
![image](https://user-images.githubusercontent.com/82647447/231171143-42e7d056-4ff4-43b7-a428-1c47dbeff653.png)

2023-04-27 03:51 UTC, sabhas requested changes

2023-04-27 03:51 UTC, sabhas commented on web/src/containers/Studio/internal/components/log/logChunk.tsx
can we convert inline styles to CSS classes wherever possible?

2023-04-27 15:25 UTC, YuryShkoda commented on web/src/containers/Studio/internal/components/log/logChunk.tsx
done

2023-04-28 05:27 UTC, sabhas approved these changes

2023-04-28 09:29 UTC, merged